### ISSUE TITLE
Failed to invoke function `apoc.cypher.runFirstColumn` using GraphAware TimeTree

### ISSUE THREAD

**Issue by jameslouiz** [neo4j-graphql/neo4j-graphql-js#181]
Hi all I'm getting this errror:
```
"Failed to invoke function `apoc.cypher.runFirstColumn`: Caused by: org.neo4j.graphdb.security.AuthorizationViolationException: Write operations are not allowed for user 'neo4j' with FULL restricted to READ."
```

Which I believe is because `ga.timetree.events.range` is a `WRITE` command as stated when I run `dbms.procedures`.

<img width="1464" alt="screenshot 2019-01-15 at 15 28 11" src="https://user-images.githubusercontent.com/1032315/51190477-35704c80-18da-11e9-9ffc-268401f53965.png">

I'm not sure how I get around this, all I want to do is return nodes attached to the timetree "instants"

```
@cypher(
      statement: """
        CALL ga.timetree.events.range({ start: 1, end: 999999999, create: false }) YIELD node
        return node
      """
    )
```

Is there a way I can get around this? 

Thanks, James

**Comment by johnymontana** [comment]
You could try defining that field on the Mutation type, instead of as a Query. Even though the `ga.timetree.events.range` procedure may not be updating the graph, because it is declared as a write operation it won't be able to be executed using `apoc.cypher.runFirstColumn` (which we use to run the  `@cypher` directive defined queries as subqueries) since that is limited to read operations only. 

We use a different approach for the `@cypher` directives on mutations that will allow write operations.

**Comment by jameslouiz** [comment]
@johnymontana  Thanks for the reply. In the end I decided to remove timetree and just use the native temporal types.
