### ISSUE TITLE
Regression: 2.3.0 returns null for all fields

### ISSUE THREAD

**Issue by wheresrhys** [neo4j-graphql/neo4j-graphql-js#189]
Pinning to 2.2.0 fixes the issue.

neo4j version: 3.5 community
node version: 8.x
bolt driver version: 1.7.2
apollo version: 1.4.0

I'm about to go on holiday, so no time to prepare a reduced test case. The tests in our private repo surface the issue though. I'll ask about giving someone from neo4j access to the codebase if you're interested in digging around

cc @GeoffThorpeFT

**Comment by johnymontana** [comment]
Yikes - that's not good :-\ 

Are you getting any error messages?

Yes, please share any code you can with me and I'll try to reproduce.

**Comment by wheresrhys** [comment]
Can you access this now https://github.com/Financial-Times/biz-ops-api?

I will prepare a guide to running tests without access to creds

**Comment by johnymontana** [comment]
@wheresrhys Yes, thanks - I can access `biz-ops-api`, but it looks like I'll also need access to `biz-ops-schema` for the typedefs and resolvers?

**Comment by wheresrhys** [comment]
that's an npm module though, so should be installed when running npm install

The only env variables you should need (I think) are

```
HEROKU_API_URL=http://localhost:8888
NEO4J_BOLT_URL=bolt://localhost:7687
```

all stored in .env.

you may need to create dummy values for any of the following, tough real values shouldn't be needed for tests

```
API_KEY
AWS_ACCESS_KEY_ID
AWS_ACCOUNT_ID
AWS_SECRET_ACCESS_KEY
AWS_USER_ARN
BIZ_OPS_API_URL
CRUD_EVENT_LOG_STREAM_NAME
DISABLE_READS
DISABLE_WRITES
ENVIRONMENT
ENVIRONMENT_TAG
FT_API_GATEWAY_KEY
FT_API_GATEWAY_URL
HEROKU_API_URL
NEO4J_BOLT_PASSWORD
NEO4J_BOLT_URL
NEO4J_BOLT_USER
NEO4J_URL
```

Thanks for taking a look

**Comment by johnymontana** [comment]
Thanks. I was able to reproduce and I think we've found the cause. The v2.3.0 release includes a feature to ignore fields that may be resolved from external sources outside of Neo4j and not include those fields in the generated Cypher query (via a `@neo4j_ignore` schema directive) . We also include some logic to detect if a resolver is already provided for a field and then add the `@neo4j_ignore` directive so that field level resolver can be called and excluded from the generated Cypher query.

However, in your case it seems that since a logger was included in the call to `makeExecutableSchema`, that logger is distributed across every field in the `resolve` path of the AST, and we incorrectly assume that a resolver has been provided for that field and assign the `@neo4j_ignore` directive, thus excluding almost all fields from the Cypher query.

We're working on a fix (will be removing this inferring functionality and only handle explicitly specified `@neo4j_ignore` directives) and should have it released soon.

**Comment by johnymontana** [comment]
A fix for this is available now in v2.3.1. Please let us know if this resolves the issue.

**Comment by wheresrhys** [comment]
Excellent, will hopefully give it a go today or early next week

**Comment by wheresrhys** [comment]
Yep - issue fixed. Thanks for the speedy response, and looking forward to using the improved ordering behaviour (which I believe is in 2.3.x?)

**Comment by johnymontana** [comment]
Great - glad that worked. Sorry for introducing the bug! 

Yes, nested ordering is now supported in 2.3.x 🎉
