### ISSUE TITLE
Nodes with node label `String` are ignored

### ISSUE THREAD

**Issue by DerMika** [neo4j-graphql/neo4j-graphql-js#351]
I have a Neo4J database which contains - among others - nodes with the label `String`. 

When I define the type as such

```
 makeAugmentedSchema({
  typeDefs: gql`
    interface Component {
      name: String
      caption: String
    }
    type String implements Component {
      name: String
      caption: String
    }`,
  config: {
    mutation: false
  }
})
```

... the String type does not appear in my schema on the Apollo Playground. 

Likely because it's a redefinition of the native String datatype...

Is this something that can be fixed, or do I have to find a workaround?

Changing the database is not possible, but I can live with another name for the "String" type in my GraphQL Schema if necessary.

**Comment by benjamin-rood** [comment]
Hi, why are you redefining/overriding the native String datatype?
If you can explain the use-case, maybe we can also help find a solution.

**Comment by DerMika** [comment]
Haha, I know right!

Unfortunately my Neo4J backend contains a set of nodes where the defining label on the node is ´String´.

**Comment by wheresrhys** [comment]
The best I can think of is along the lines of what you have, but then using the cypher directive to manually write relationship resolvers that actually query for `String` nodes

```
type SomeThing {
     myStrings: [StringComponent] @cypher(statement: "MATCH (this)-[:YOUR_REL_NAME]->(s:String) RETURN s")
}
```
This has the downside of not giving access to any of the filtering features of the library, but I'm optimistic it will work for setting up an API that allows you to traverse from other things to Strings. But it won't work if the library actually checks the labels of returned nodes before converting to a response (rather than just trusting that the query has returned nodes of the right type)

For traversing relationships beginning at a String/StringComponent you'll have to try some other trick - I'm not entirely sure how neo4j-graphql-js picks the start node for a query, so can't help you there I'm afraid.

**Comment by DerMika** [comment]
Thanks, I guess that's the best I can expect :)
