### ISSUE TITLE
Random failures - mutations 

### ISSUE THREAD

**Issue by udaykor** [neo4j-graphql/neo4j-graphql-js#462]
Following the GRAND stack starter, I have created two mutations for seed. I have a bug that I am having hard-time to understand. 

My seeding:
1. Fails for a few of the entries (3 of 517 entries fail for a mutation)
2. Fails for a more than the few but random ones (10 of 517 for the same mutation). 
3. Succeeds with all entries. 

I read my data from a CSV file. I do not have a consistent behaviour. My neo4j is over SSL. I do not understand why random entries fail the mutation. Am I the first one to come across this issue? What am I doing wrong potentially?

**Comment by asianfilm** [comment]
I had the exact same issue in the past 12 hours with mutations when seeding my database wholly on my laptop (and hence with zero latency). The solution I found was to throttle my mutations. I set it to 50 per second and didn't try a higher rate yet. I don't know if the problem lies with Apollo Server or `neo-graphql-js`, but I'm sure Neo4j itself can handle the load.

Note these were silent failures. The API server's log showing my stream of queries but gave no indication that any failed. But if I kickstarted another batch of mutations, the API server would crash. The management console of Neo4j Desktop wasn't helpful; there was no indication of anything wrong in the Neo4j log or in the list of running queries (`CALL dbms.listQueries()`).

The long-term solution is likely the suggestion (roadmap?) for auto-generated batch mutations from an [issue](https://github.com/neo4j-graphql/neo4j-graphql-js/issues/194) from Feb 2019. I see that Hasura, for example, has this [built-in](https://hasura.io/blog/bulk-insert-mutations-with-graphql-e22727ce5b12/). Towards the same solution, it would also be nice to have auto-generated mutations that were as expressive as the auto-generated queries so that one could issue less of them.

To that end, another short-term solution is writing more expressive custom mutations that reduce the need for many smaller migrations. The problem is that you'll need to keep you Cypher code (and any APOC-backed import scripts) in sync with your schema. That means writing a bunch of tests that would otherwise be superfluous.

**Comment by asianfilm** [comment]
After more experimentation with 10,764 migrations.

+ Rate-limited to 250 mutations per second, it silently fails at 363 mutations, or 3.37%
+ Rate-limited to 100 mutations per second, it silently fails at around 2000 mutations, or just under 20%
+ Rate-limited to 50 mutations per second, it completes all 10,764 migrations.

With these kind of numbers, the solution has to be auto-generated batch mutations. I don't know if it's possible in `neo4j-graphql-js` to write a custom mutation that handles multiple mutations by passing in an array of values.

FYI, I'm running this locally on a mid-2012 MacBook Pro with 8GB (with an upped allocation of RAM to Neo4j). That sounds old, but I believe the latest 16" MacBook Pros are only about twice as fast. (By my reckoning, Moore's Law went from double processor speeds every 18 months to every 7.5 years.) Interested in hearing other people's experiences and solutions.

**Comment by udaykor** [comment]
I am on a 2015 Macbook pro with a remote graph. I think you are right but also sometimes I have all my writes go in perfectly

**Comment by asianfilm** [comment]
> I am on a 2015 Macbook pro with a remote graph. I think you are right but also sometimes I have all my writes go in perfectly

I haven’t had the issue recently, FYI. But I’m also shifting away from my approach of only importing data via mutations.

**Comment by michaeldgraham** [comment]
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/608
