### ISSUE TITLE
[Question] Compatibility with Flutter

### ISSUE THREAD

**Issue by scheung38** [neo4j-graphql/neo4j-graphql-js#470]
How to use Flutter instead of React?  Is this the correct stack or use the grandstack-architect repo?

**Comment by asianfilm** [comment]
You can certainly swap out React for another solution (like Vue, Angular, Elm, etc).

Before it shut down, Smooth Terminal put out a series of videos in which they implemented a GraphQL interface in various frontends including Flutter. Questions about GraphQL pop up sometimes on the Flutter Reddit, and although I'm not aware of any open source libraries, people report that it's quite straightforward to write their own with Dart.

But, check the Reddit archives in case any libraries are mentioned. And, for sure, you can use Grandstack since it has a clean separation between the client and server layers with the GraphQL Schema acting as the clean interface between the two.

**Comment by johnymontana** [comment]
This library helps to create GraphQL APIs backed by Neo4j. Any GraphQL client can then be used to query the GraphQL API - there's nothing specific in this library that addresses which clients can be used with it.

I'm not familiar with the Flutter GraphQL tooling, but any Flutter GraphQL client (or really any Flutter tooling that can make a HTTP request) can be used.
