### ISSUE TITLE
Filtering _Neo4jDateTime within AND, OR condition resulting in "Neo4jError: No such field: formatted"

### ISSUE THREAD

**Issue by CraigDeverall** [neo4j-graphql/neo4j-graphql-js#495]
`Assignment(filter: {
      AND: [
        { OR: [
          {AND: {start_lt: {formatted:$end}, start_gt: {formatted:$start}}},
          {AND: {end_lt: {formatted:$end}, end_gt: {formatted:$start}}},
          {AND: {start_lt: {formatted:$start}, end_gt: {formatted:$end}}},
    		]}, 
				{timeline: {name: $timelineName}}
      ]}) {
    id
  }`

This causes an error: `"Neo4jError: No such field: formatted"`

Where as:
` Assignment(filter:  {start_lt: {formatted:$end}, start_gt: {formatted:$start}}) {
    id
  }`
does not.

`assignments(
      filter: {
        AND: [
          {
            OR: [
              { AND: { start_lt: { year: 2021 }, start_gt: { year: 2020 } } }
              { AND: { end_lt: { year: 2021 }, end_gt: { year: 2020 } } }
              { AND: { start_lt: { year: 2020 }, end_gt: { year: 2021 } } }
            ]
          }
          { timeline: { name: $timelineName } }
        ]
      }
    )`

Is also a valid working query, so it seems just an issue with using {formatted: ""} inside of AND and OR conditions.

**Comment by NawarA** [comment]
After upgrading to `2.16.4`, I'm now seeing this error.

This works: 👍 
![image](https://user-images.githubusercontent.com/2067616/95245460-01347200-07c8-11eb-8169-236e6bd2e310.png)

This fails 👎 
![image](https://user-images.githubusercontent.com/2067616/95245532-1d381380-07c8-11eb-8b29-f35d9aa70f13.png)
This fails 👎 
![image](https://user-images.githubusercontent.com/2067616/95245573-29bc6c00-07c8-11eb-9cc8-296e59713324.png)

with the error
![image](https://user-images.githubusercontent.com/2067616/95245624-35a82e00-07c8-11eb-945f-36577c14c108.png)

Though, it looks like the DB still recognizes `formatted`, so it must be a transpiling issue
![image](https://user-images.githubusercontent.com/2067616/95245802-7acc6000-07c8-11eb-95e3-637b4724342c.png)

Error, as of `2.16.4`. I checked `2.16.3`, and all tests pass. Its an issue with the current release

**Comment by NawarA** [comment]
Also, I'd like to clarify...this issue does not have to do with `Filtering _Neo4jDateTime within AND, OR condition resulting in`. Instead, creating any kind of node with a temporal value fails...so this is probably a critical bug, if anyone pushed 2.16.4 to production, and they rely on temporal values...their production code for node creation is affected / broken due to this. I'm happy to own a separate issue, as it relates to node creation, not filtering, but it is the same error message, so I posted it here

**Comment by NawarA** [comment]
one final note, if anyone is affected by this, my temporarily work-around is to use stop using `formatted` and manually destructure all dates...which is lame...but at least it'll prevent the code from crashing

**Comment by NawarA** [comment]
I still see this as an issue on 12.17.1

For example, on our client (apollo-client)
![image](https://user-images.githubusercontent.com/2067616/99115276-034bd680-25a7-11eb-80f3-cf4396dca686.png)

Using the correct way to save a timestamp:
![image](https://user-images.githubusercontent.com/2067616/99115594-82410f00-25a7-11eb-8a34-0ceb4a516548.png)

yields `No such field: formatted`
![image](https://user-images.githubusercontent.com/2067616/99115514-62a9e680-25a7-11eb-94e5-54af10512cb0.png)

but if we use the workaround
![image](https://user-images.githubusercontent.com/2067616/99115682-ad2b6300-25a7-11eb-9190-a0cb8d69318e.png)
![image](https://user-images.githubusercontent.com/2067616/99115715-b7e5f800-25a7-11eb-9919-07058a18ffe7.png)

Then everything goes through, with status 200

So I'd say actually, this issue shouldn't be marked as closed for now, as it still open in 12.17.1

**Comment by NawarA** [comment]
@johnymontana please reopen, as it stills an open issue apparently on `12.17.1`

Thank you 🙏

**Comment by udaykor** [comment]
@johnymontana I have this on `2.17.1`. Apparently I can create datetimes by destructuring from new Date(). Would love to use formatted

**Comment by udaykor** [comment]
@johnymontana  Ignore my comments, @NawarA  I have success with `{formatted: new Date().toISOString()`. 

I had rebuilt my server and forgot to use the right config. I had to add apoc to the whitelist as well as under unrestricted. This is working perfectly for me now.

**Comment by udaykor** [comment]
@NawarA I reckon this is something wrong with the graphql client we are using. I am using Apollo Boost

**Comment by udaykor** [comment]
@NawarA My issue is only with Update and Merge, I can created ISOString dates though

https://github.com/neo4j-graphql/neo4j-graphql-js/issues/537

**Comment by NawarA** [comment]
We're using `@apollo/client`: `^3.2.9`...so the current apollo client. You should considering switching, since apollo-boost is now "retired" and has been replaced by `@apollo/client`.

Screenshot from the [apollo site](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/).
![image](https://user-images.githubusercontent.com/2067616/100376168-e3171100-2fc3-11eb-8a1d-a8fa4bc9bbdb.png)

I believe you're correct, the open issue allows developers to save DateTime using `formatted`, but thereafter, `neo4j-graphql-js` `2.17.1` **crashes when you try to update** the same property using `formatted`.

**Comment by udaykor** [comment]
Happy Thanks giving mate, Yes I just made changes to move to apollo client. The issue is with APOC not this library though from what I found from my neo4j logs

**Comment by igokul1973** [comment]
Hi to all! Also having this issue.
@michaeldgraham 
Hi! I analysed the issue and it seems to have been introduced with your new mutation.js file - https://github.com/neo4j-graphql/neo4j-graphql-js/blob/master/src/translate/mutation/mutation.js around 4 months ago. It apparently rewrites the logic of creating the cypher mutation with params, which causes the error in question.
If you look at the line 593 in your commit 36a754a then one can suppose that here you should've taken into consideration the `updateParams` variable from above in the code. Given in `params.params` there is an original field of temporal type such as: {updated_at: {formatted: '2020-12-12...'}}? the `updateParams.params` has the `updated_at` converted to {updated_at: '2020-12-12...'}. Since the query itself contains `..., updatedAt: datetime($params.updatedAt), ...` the params for the `updated_at` should be like in the `updateParams.params.updated_at`. Please take it into consideration and fix the error.

**Comment by chunkychode** [comment]
@igokul1973 
This library is being replaced with [@neo4j/graphql](https://www.npmjs.com/package/@neo4j/graphql), do i doubt this will be fixed.  i've been using a fork that deals with this issue this [pr](https://github.com/neo4j-graphql/neo4j-graphql-js/pull/596)
