### ISSUE TITLE
mutation of nested fields default resolver conflicts

### ISSUE THREAD

**Issue by zhenyulin** [neo4j-graphql/neo4j-graphql-js#91]
I'm relatively new to this, and was experimenting it to create a user follower feature.

I have a type like the following:
```
	type User {
		id: ID!
		name: String
		email: String!
		followers: [User] @relation(name: "FOLLOWS", direction: "IN")
	}
```
using the default mutation resolver, it would give me a `AddUserUser` which only has one input userId.

Is it possible 1) to alias User type as Follower type so that we can get a `AddUserFollower` by default? 2) to have `userId` and `userId2` to distinguish the two User instance here?

**Comment by YizYah** [comment]
@johnymontana this raises the issue of ambiguous parameters.

I have a proposal: 
1. use the name of the field in place of the name of the type.
2. use a singular form of the field name.  For instance, rather than `followersid` ideal would be `followerid`.  Do do that, you could either use a fairly dumb quick algorithm that's correct most of the time (at it's simplest, remove an es or an s, but replace ies with y) or ideally use something like https://github.com/blakeembrey/pluralize.

As an aside, would it be possible to use camelCase?  I just think that `followerId` is easier to read than `followerid`.

**Comment by zhenyulin** [comment]
it looks it is not possible to do Type alias in graphql SDL, can we potentially have another field in the @relation directive? so that this can be picked up by cypher generator

```js
type User {
  id: ID!
  followers: [User] @relation(name: "FOLLOWS", direction: "IN", alias: "follower")
}
```

**Comment by johnymontana** [comment]
This should now be fixed, you should now see an `AddUserFollowers` mutation with `from` and `to` parameters that take an input type. Please reopen if you're still having issues.
