### ISSUE TITLE
js generated schema support?

### ISSUE THREAD

**Issue by stephen-dahl** [neo4j-graphql/neo4j-graphql-js#95]
Is it possible to use this with schemas generated using js instead of SDL? for example
```
const {
	GraphQLObjectType,
	GraphQLListType,
	GraphQLString,
} = require('graphql');

const Recipe = new GraphQLObjectType({
	fields: () => ({
		name: { type: GraphQLString },
		steps: { type: new GraphQLListType(GraphQLString) },
	}),
});
```
how would you apply annotations in this context?

**Comment by johnymontana** [comment]
Hey @stephen-dahl - yes, you just need to create the relevant `GraphQLDirective` and add it to your `GraphQLObjectType` object.  Once you've created the `GraphQLSchema` object you can pass that to [`augmentSchema`](https://grandstack.io/docs/neo4j-graphql-js-api.html#augmentschemaschema-config-graphqlschema) or [`makeAugmentedSchema`](https://grandstack.io/docs/neo4j-graphql-js-api.html#makeaugmentedschemaoptions-graphqlschema) instead of type definitions to create the auto-generated resolvers and other schema augmentations.

There's an example in this issue: https://github.com/graphql/graphql-js/issues/1343#issuecomment-401749793
